spring:
  application:
    name: SemanticWarcSearch
  # Disable web server (command-line app only)
  main:
    web-application-type: none
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        model: qwen3-embedding:0.6B   # This standard one has 1024 dimensions. Please check your solr schema.xml for same value for the field type you are indexing to.

# Solr
solr:
  base-url: http://localhost:8983/solr
  collection: warc
